export default [
    {
        name:'Home',
        iconType:'FontAwesome',
        iconName:'home'
    },
    {
        name:'Usuarios',
        iconType:'FontAwesome5',
        iconName:'user-friends'
    },
    {
        name:'Voos',
        iconType:'MaterialCommunityIcons',
        iconName:'airplane'
    },
    {
        name:'Tickets',
        iconType:'Entypo',
        iconName:'ticket'
    },
    {
        name:'Cidades',
        iconType:'FontAwesome5',
        iconName:'city'
    },
    {
        name:'Settings',
        iconType:'Feather',
        iconName:'settings'
    },
    {
        name:'Login',
        iconType:'Entypo',
        iconName:'login'
    },
    {
        name:'Sign in',
        iconType:'FontAwesome',
        iconName:'sign-in'
    },
    {
        name:'Log out',
        iconType:'Entypo',
        iconName:'log-out'
    }
 ]